version: 2

sources:
  - name: erp
    description: Banco réplica do erp da Adventure Works.
    schema: sap_adw
    tables:
      - name: product
        description: Tabela de pedidos
        columns:
          - name: productid 
            description: Descrição.

          - name: productsubcategoryid 
            description: Descrição.

          - name: name
          - name: productnumber 
            description: Descrição.

          - name: color 
            description: Descrição.

          - name: safetystocklevel 
            description: Descrição.

          - name: standardcost 
            description: Descrição.

          - name: listprice 
            description: Descrição.

          - name: daystomanufacture 
            description: Descrição.

          - name: productline	
            description: Descrição.

          - name: class 
            description: Descrição.

          - name: style 
            description: Descrição.

      