version: 2

sources:
  - name: erp
    description: Banco réplica do erp da Adventure Works.
    schema: sap_adw
    tables:
      - name: product
        description: Tabela de pedidos
        columns:
          - name: productid 
            description: Descrição.

          - name: productsubcategoryid 
            description: Descrição.

          - name: name
          - name: productnumber 
            description: Descrição.

          - name: color 
            description: Descrição.

          - name: safetystocklevel 
            description: Descrição.

          - name: standardcost 
            description: Descrição.

          - name: listprice 
            description: Descrição.

          - name: daystomanufacture 
            description: Descrição.

          - name: productline	
            description: Descrição.

          - name: class 
            description: Descrição.

          - name: style 
            description: Descrição.

      - name: address
        description: Tabela de endereços.
        columns:
          - name: addressid
            description: ID de endereço.
          
          - name: stateprovinceid
            description: ID do estado.

          - name: city
            description: Nome da cidade.

      - name: businessentitycontact
        description: Tabela de endereços.
        columns:
          - name: businessentityid				
            description: ID da entidade de negócio.

          - name: personid
            description: ID da pessoa.

      - name: person
        description: Tabela de pessoas.
        columns:
          - name: businessentityid				
            description: ID da entidade de negócio.

          - name: firstname				
            description: Primeiro nome da pessoa.

          - name: middlename				
            description: Segundo nome da pessoa.

          - name: lastname				
            description: Último nome da pessoa.


    

      